/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import9 from '../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import10 from '@angular/core/src/linker/query_list';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/router/src/router_state';
import * as import15 from '@angular/common/src/location/location_strategy';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/router/src/router_outlet_map';
import * as import18 from '@angular/core/src/linker/component_factory_resolver';
import * as import19 from '@angular/router/src/directives/router_link';
import * as import20 from '@angular/router/src/directives/router_link_active';
import * as import21 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.AppComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'my-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent();
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('my-app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _RouterLinkWithHref_22_3:import8.Wrapper_RouterLinkWithHref;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _el_27:any;
  _RouterLinkWithHref_27_3:import8.Wrapper_RouterLinkWithHref;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _el_45:any;
  _RouterLinkWithHref_45_3:import8.Wrapper_RouterLinkWithHref;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _el_49:any;
  _RouterLinkWithHref_49_3:import8.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_49_4:import9.Wrapper_RouterLinkActive;
  _query_RouterLink_49_0:import10.QueryList<any>;
  _query_RouterLinkWithHref_49_1:import10.QueryList<any>;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  /*private*/ _vc_56:import11.ViewContainer;
  _RouterOutlet_56_5:import12.Wrapper_RouterOutlet;
  _text_57:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'nav',new import3.InlineArray2(2,'class','navbar '),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'a',new import3.InlineArray4(4,'class','navbar-brand','href','#'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'kidslaughs',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n\n\n            ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_4,'ol',new import3.InlineArray2(2,'class','nav navbar-nav navbar-right'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'ol',new import3.InlineArray2(2,'class','breadcrumb'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_16,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,' Home',(null as any));
    this._text_19 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_14,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n                    ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'a',new import3.InlineArray2(2,'routerLink','/contact-us'),(null as any));
    this._RouterLinkWithHref_22_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._text_23 = this.renderer.createText(this._el_22,'contact us',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n                    ',(null as any));
    this._text_25 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_14,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_26,'a',new import3.InlineArray2(2,'routerLink','/feedback'),(null as any));
    this._RouterLinkWithHref_27_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._text_28 = this.renderer.createText(this._el_27,' Feedback',(null as any));
    this._text_29 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._text_30 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._text_31 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_33 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_37 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_38 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_39 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_40 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_41 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_0,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'\n    ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_42,'button',new import3.InlineArray4(4,'class','btn btn-warning ','type','button'),(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_44,'a',new import3.InlineArray2(2,'routerLink','/submit-joke'),(null as any));
    this._RouterLinkWithHref_45_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._text_46 = this.renderer.createText(this._el_45,' submit Jokes',(null as any));
    this._text_47 = this.renderer.createText(this._el_42,'\n\n    ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_42,'button',new import3.InlineArray4(4,'class','btn btn-warning active','type','button'),(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_48,'a',new import3.InlineArray4(4,'routerLink','/joke-detail','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_49_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_49_4 = new import9.Wrapper_RouterLinkActive(this.parentView.injectorGet(import13.Router,this.parentIndex),new import16.ElementRef(this._el_49),this.renderer);
    this._query_RouterLink_49_0 = new import10.QueryList<any>();
    this._query_RouterLinkWithHref_49_1 = new import10.QueryList<any>();
    this._text_50 = this.renderer.createText(this._el_49,' jokes',(null as any));
    this._text_51 = this.renderer.createText(this._el_42,'\n\n    ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_42,'button',new import3.InlineArray4(4,'class','btn btn-primary active','type','button'),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'most liked jokes',(null as any));
    this._text_54 = this.renderer.createText(this._el_42,'\n    ',(null as any));
    this._text_55 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_0,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_56 = new import11.ViewContainer(56,0,this,this._el_56);
    this._RouterOutlet_56_5 = new import12.Wrapper_RouterOutlet(this.parentView.injectorGet(import17.RouterOutletMap,this.parentIndex),this._vc_56.vcRef,this.parentView.injectorGet(import18.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_57 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_22,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_22));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_27,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_27));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_45,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_45));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_49,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_49));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.RouterLinkWithHref) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._RouterLinkWithHref_22_3.context; }
    if (((token === import19.RouterLinkWithHref) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._RouterLinkWithHref_27_3.context; }
    if (((token === import19.RouterLinkWithHref) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._RouterLinkWithHref_45_3.context; }
    if (((token === import19.RouterLinkWithHref) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._RouterLinkWithHref_49_3.context; }
    if (((token === import20.RouterLinkActive) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._RouterLinkActive_49_4.context; }
    if (((token === import21.RouterOutlet) && (56 === requestNodeIndex))) { return this._RouterOutlet_56_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_22_0_0:any = '/contact-us';
    this._RouterLinkWithHref_22_3.check_routerLink(currVal_22_0_0,throwOnChange,false);
    this._RouterLinkWithHref_22_3.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_27_0_0:any = '/feedback';
    this._RouterLinkWithHref_27_3.check_routerLink(currVal_27_0_0,throwOnChange,false);
    this._RouterLinkWithHref_27_3.ngDoCheck(this,this._el_27,throwOnChange);
    const currVal_45_0_0:any = '/submit-joke';
    this._RouterLinkWithHref_45_3.check_routerLink(currVal_45_0_0,throwOnChange,false);
    this._RouterLinkWithHref_45_3.ngDoCheck(this,this._el_45,throwOnChange);
    const currVal_49_0_0:any = '/joke-detail';
    this._RouterLinkWithHref_49_3.check_routerLink(currVal_49_0_0,throwOnChange,false);
    this._RouterLinkWithHref_49_3.ngDoCheck(this,this._el_49,throwOnChange);
    const currVal_49_1_0:any = 'active';
    this._RouterLinkActive_49_4.check_routerLinkActive(currVal_49_1_0,throwOnChange,false);
    this._RouterLinkActive_49_4.ngDoCheck(this,this._el_49,throwOnChange);
    this._RouterOutlet_56_5.ngDoCheck(this,this._el_56,throwOnChange);
    this._vc_56.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_49_0.dirty) {
        this._query_RouterLink_49_0.reset(([] as any[]));
        this._RouterLinkActive_49_4.context.links = this._query_RouterLink_49_0;
        this._query_RouterLink_49_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_49_1.dirty) {
        this._query_RouterLinkWithHref_49_1.reset([this._RouterLinkWithHref_49_3.context]);
        this._RouterLinkActive_49_4.context.linksWithHrefs = this._query_RouterLinkWithHref_49_1;
        this._query_RouterLinkWithHref_49_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_49_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_22_3.checkHost(this,this,this._el_22,throwOnChange);
    this._RouterLinkWithHref_27_3.checkHost(this,this,this._el_27,throwOnChange);
    this._RouterLinkWithHref_45_3.checkHost(this,this,this._el_45,throwOnChange);
    this._RouterLinkWithHref_49_3.checkHost(this,this,this._el_49,throwOnChange);
  }
  destroyInternal():void {
    this._vc_56.destroyNestedViews();
    this._RouterLinkWithHref_22_3.ngOnDestroy();
    this._RouterLinkWithHref_27_3.ngOnDestroy();
    this._RouterLinkWithHref_45_3.ngOnDestroy();
    this._RouterLinkWithHref_49_3.ngOnDestroy();
    this._RouterLinkActive_49_4.ngOnDestroy();
    this._RouterOutlet_56_5.ngOnDestroy();
  }
  handleEvent_22(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_22_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_27(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_27_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_45(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_45_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_49(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_49_3.handleEvent(eventName,$event) && result);
    return result;
  }
}